name: smartmetric_case
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # ** Utility **
  gap: ^3.0.1
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  easy_logger: ^0.0.2
  logger: ^2.4.0
  flutter_native_splash: ^2.4.4
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  # ** Network Dependencies **
  dio: ^5.8.0+1
  http_parser: ^4.0.2

  # ** Core Dependencies **
  equatable: ^2.0.7
  shared_preferences: ^2.5.3

  # ** Navigation **
  auto_route: ^9.3.0

  # ** Config **
  easy_localization: ^3.0.7

  # ** State **
  flutter_bloc: ^9.1.1

  # # ** Private Packages **
  # common:
  #   path: module/common

  # gen:
  #   path: module/gen

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  flutter_launcher_icons: ^0.14.4

flutter_native_splash:
  color: "#485D92"
  image: module/gen/assets/images/lawai.png

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/translations/
